### ISSUE TITLE
Peptide discovery 

### ISSUE THREAD

**Issue by shahik** [Sulstice/cocktail-shaker#283]
Hi, 
     thanks for the awesome library! How can I generate targeted peptides using my custom dataset (chembl molecules) ? 
Example:  Target is some protein and training data consist of compound smiles. So using my custom dataset how can I generate peptides that would bind with target protein? 
Greetings!

**Comment by Sulstice** [comment]
Ya! Okay, so let me clarify:

`you have chembl molecules` meaning you downloaded them in SMILES? these chembl molecules are they fragments or can you enlighten me into some rows in your dataset. 

Also see if one of my example notebooks help or get you started: 

https://github.com/Sulstice/cocktail-shaker/blob/master/juptyer_notebooks/cocktail_api/include_amino_acids.ipynb

**Comment by shahik** [comment]
thanks for reaching out! Yes from chembl I have downloaded 50 smiles that bind to a specific target protein and cleaned them. My smiles dataset has larger protein & peptides mixed up, now can I train the model for the purpose of generating peptides ? 
If I am not wrong here standard_value < 50 is a peptide, few examples


                                       Smiles                                                            Standard_Value 


     Cc1noc(-c2ccc3c(c2)c2c(n3CCCSc3cc(F)cc(F)c3)CCC(F)(F)C2)n1                         15             (peptide)
     CCc1cc(CC)nc(OCCCn2c3c(c4cc(-c5nc(C)no5)ccc42)C(=O)CCC3)n1                   1.5             (peptide)
     CCOC(=O)c1ccc2c(c1)c1ccccc1n2CCCN1C[C@H](C)N[C@H](C)C1                    600            (protein)
     Cc1noc(-c2ccc3c(c2)c2c(n3CC(F)COc3cc(F)cc(F)c3)CCCC2)n1                            1.5              (peptide)
     Cc1noc(-c2ccc3c(c2)c2c(n3CCCc3nc4cc(F)ccc4[nH]3)CCCC2)n1                        1.5             (peptide)

**Comment by Sulstice** [comment]
Hmmm, I might be a little confused on your peptide strings. Are you sure those are peptides? they don't seem to be any formal peptide backbone chain?

For example here's an example pattern of peptide I am looking for:

```
O=C1C([*:1])NC(=O)C([*:2])NC(=O)C([*:3])N1
```

From what I understand correctly, you need to pull out features of the existing chembl peptides - i.e functional groups or SMARTS pattern recognition and then generate peptides using my library. 

An avenue you can take is take the chembl smiles and identify functional groups. You can use another package of mine to get a collection of SMARTs if you would like: https://github.com/Sulstice/global-chem and then do the matching. I already wrote the pattern and the IUPAC name to accommodate my earlier younger years. 

From there you can generate a peptide backbone string using my examples and insert the functional groups of interest against your protein. 

Your protein is in a 1D format so you're approach is to use SMILES 1D to protein 1D correct to identify binding moieties? not a bad idea is this where you are headed?

**Comment by shahik** [comment]
Sorry, my bad standard values above represent the potency of proteins, not peptides and I appreciate you for introducing me to this new approach! 
The problem is there are very less peptides in chembl for specific target receptor. So I have to work with proteins thus smiles. 
Target receptor : CHEMBL1914272     Scavenger receptor class B member 1      SINGLE PROTEIN	Homo sapiens   IC50 (values-55) 
After I discover binding protein for my target receptor can I convert it to a peptide? Any protein to peptide conversion strategies/tools/git etc? Or talk to a chemist? thanks!  

To your approach:
 
I get all the peptides from chembl and convert them to SMARTS and generate peptides using your library but how would discovered peptide bind with target receptor? Or how can I add a functional group of interests so they should bind with the target receptor? 
As I want a peptide that is less toxic, soluble, and good binding affinity what will be the best approach between these two? thanks!

**Comment by Sulstice** [comment]
hahah sounds like you are interested in cheminformatics. 

So I do have a paper soon to help folk like yourself but you'll have to wait for that. In the meantime your gonna have to hack it yourself in the meantime - I can't release that code just yet but I promise I will open source it.

In a peptide backbone chain the SMILES, canonically, should have a pattern repeated across strings. I'll update this comment later with an example. SMARTS is a regex functional group matching if you're not used to the lanugage of SMARTS it's going to be a little tricky. 

SMARTS can tell you which functional groups are present in your peptide. You need to correlate a peptide string with functional groups and the other thing you need to record is the position (1, 2, 3, 4, 5) a long the peptide that functional group exists. 

When you have that info then you can start using my package.

Because you will provide the cocktail shaker with a peptide of some length and you will pass it the `ligand library` which will generate all combinations including if you wish stereoisomers or SMILES isomers and other enumerations. Then you can start screening those peptides against the protein. 

Your machine learning framework is going to need validation albeit from the Molecular Dynamic community or the Experimentalists (synthesists or biologists). 

I built this tool when I was younger because I am a chemist and a software engineer haha decided to learn both in my earlier years. So what I would do is generate in silico and in wet lab 100K + combinations of peptides and correlate the machine learning approach with 2D NMR spectra. 

```
s less toxic, soluble, and good binding affinity ```

don't we all? so you need pka prediction and other factors. I am not an expert in this subsection of cheminformatics - although I am learning and hope to be in the next coming years. But what can you do is aggregate combinations of peptides with peptide therapeutic existing data and correlate whether your FGs of interest are, in fact, perhaps better.

You need to tackle the first problem - What functional groups are present in my peptide SMILES? If you look at `GlobalChem` I've given you a method.
